name: "metro"
port: 8088
version: "v0.0.1"

mysql:
  host: "localhost"
  port: "3306"
  user: "root"
  password: "123456"
  database: "metro"

redis:
  host: "127.0.0.1"
  port: 6379
  password: "123456"
  database: 9